sudo: required

language: cpp

compiler:
  - clang
  - gcc

before_script:
  # install glm
  - git clone ttps://github.com/kunlin596/glm.git
  - cd glm && mkdir build && cd build && cmake .. && make install
  - cd ../..
  
  # install opencv
  - git clone https://github.com/opencv/opencv.git
  - cd opencv && mkdir build && cd build && cmake -DOPENCV_ENABLE_NONFREE .. && make install
  - cd ../..

  # configure project
  - mkdir build
  - cd build
  - cmake ..

# Build steps
script: 
  - make -j8
