sudo: required

dist: xenial
language: cpp

compiler:
  - clang
  # - gcc TODO: only test clang for now

before_script:
  - sudo apt update
  - sudo apt install -y libboost-all-dev qt5-default qtbase5-dev qtdeclarative5-dev libqt5opengl5-dev libeigen3-dev

  - git clone https://github.com/g-truc/glm.git
  - cd glm
  - mkdir build && cd build
  - cmake ..
  - sudo make -j4 install
  - cd ../..

  - git clone https://github.com/opencv/opencv_contrib.git

  # install opencv
  - git clone https://github.com/opencv/opencv.git
  - cd opencv 
  - git checkout 4.1.0
  - mkdir build && cd build
  - cmake -D CMAKE_BUILD_TYPE=RELEASE -DBUILD_EXAMPLES=OFF -DBUILD_opencv_apps=OFF -DBUILD_DOCS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DOPENCV_ENABLE_NONFREE=ON -DOPENCV_EXTRA_MODULES_PATH=`pwd`/../opencv_contrib/modules ..
  - sudo make -j8 install
  - cd ../..

  # configure project
  - mkdir build
  - cd build
  - cmake ..

# Build steps
script: 
  - make -j8
