sudo: required

dist: xenial
language: cpp

compiler:
  - clang
  # - gcc TODO: only test clang for now

before_script:
  - sudo apt update && sudo apt upgrade
  - sudo apt install libboost-dev libglm-dev libqt5-default

  # install opencv
  - git clone https://github.com/opencv/opencv.git
  - cd opencv && mkdir build && cd build && cmake -DOPENCV_ENABLE_NONFREE=ON .. && sudo make install
  - cd ../..

  # configure project
  - mkdir build
  - cd build
  - cmake ..

# Build steps
script: 
  - make -j8
